[mining]
block_time_secs = 10
block_adjustment_interval = 10
start_difficulty_bit = 22
mining_reward = 50
reward_halvening_interval = 100
[simulation]
fake_mining = true
[network]
port = 50051
seed_list = ["[::]:1337"]
