[mining]
block_time_secs = 30
block_adjustment_interval = 10
start_difficulty_bit = 22
mining_reward = 50
reward_halvening_interval = 100
[simulation]
fake_mining = true
[network]
port = 1337
seed_list = ["http://[::]:1337"]
[account]
keys_path = "./configs/keys.pkcs8"
